#!/usr/bin/env bash

version="$1"



parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

checksum_path="${parent_path}/checksums/autohotkey_${version}.sha256.txt"

if [[ ! -f "$checksum_path" ]]; then
  echo "FATAL: checksum file '${checksum_path}' not found" > /dev/stderr
  exit 1
fi

sha256checksum="$(cat $checksum_path)"

if grep -E '^2' <<< $version; then
  # v2
  url="https://github.com/Lexikos/AutoHotkey_L/releases/download/v${version}/AutoHotkey_${version}.zip"
  location="autohotkey_${version}.zip"
  extract_name="AutoHotkey64.exe"
  final_name="AutoHotkeyV2.exe"
else
  # v1
  url="https://github.com/Lexikos/AutoHotkey_L/releases/download/v${version}/AutoHotkey_${version}_setup.exe"
  location="autohotkey_${version}.exe"
  extract_name="AutoHotkeyU64.exe"
  final_name="AutoHotkey.exe"
fi



curl -L -o "${location}" "${url}"



if [[ ! $(echo "${sha256checksum} ${location}" | sha256sum -c) ]]; then
  echo "FATAL: sha256 checksum did not match. Exiting." > /dev/stderr
  exit 1
fi

7z x "${location}" "${extract_name}"

mv "${extract_name}" ${final_name}