on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9rc]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Format version
        id: get_version
        run: |
          v1="$(python3 -c 'import ahk_binary; print(ahk_binary.V1)')"
          v2="$(python3 -c 'import ahk_binary; print(ahk_binary.V2)')"
          echo "v1=${v1}" >> $GITHUB_OUTPUT
          echo "v2=${v2}" >> $GITHUB_OUTPUT
      - name: download_ahk
        env:
          AHK_VERSION_V1: ${{ steps.get_version.outputs.v1 }}
          AHK_VERSION_V2: ${{ steps.get_version.outputs.v2 }}

        run: |
          apt update && apt install --no-install-recommends -y p7zip-full
          chmod +x ci/download_ahk
          ci/download_ahk $AHK_VERSION_V1
          ci/download_ahk $AHK_VERSION_V2
      - name: build
        run: |
          python -m pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release PyPI
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload dist/*
