on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: download_ahk
        run: |
          python3 -c "from ahk_binary import __version__;raise SystemExit(1 if __version__ != '${GITHUB_REF}' else 0)"
          apt update && apt install --no-install-recommends -y p7zip-full
          ci/download_ahk $GITHUB_REF
      - name: build
        run: |
          python -m pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release PyPI
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload dist/*
