on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Format vertsion
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: download_ahk
        env:
          AHK_VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          python3 -c "from ahk_binary import __version__;raise SystemExit(1 if __version__ != '${AHK_VERSION}' else 0)"
          apt update && apt install --no-install-recommends -y p7zip-full
          chmod +x ci/download_ahk
          ci/download_ahk $AHK_VERSION
      - name: build
        run: |
          python -m pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release PyPI
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload dist/*
